<?php

return [
    'name' => env('PORTFOLIO_NAME') ?: 'Pedro Felipe',
    'role' => env('PORTFOLIO_ROLE') ?: 'Desenvolvedor Full Stack',
    'current_role' => 'Analista de Implantação',
    'location' => env('PORTFOLIO_LOCATION') ?: 'Natal, RN · Brasil',
    'company' => env('PORTFOLIO_COMPANY') ?: 'Vox Tecnologia',
    'current_roles' => [
        [
            'role' => 'Analista de Implantação',
            'company' => env('PORTFOLIO_COMPANY') ?: 'Vox Tecnologia',
            'location' => env('PORTFOLIO_LOCATION') ?: 'Natal, RN · Brasil',
        ],
        [
            'role' => 'Desenvolvedor Full Stack Freelancer',
            'company' => 'Projetos independentes',
            'location' => 'Remoto',
        ],
    ],
    'presentation_timezone' => env('PORTFOLIO_TIMEZONE', 'America/Fortaleza'),
    'photo' => '/images/pedro-felipe.png',
    'email' => env('PORTFOLIO_EMAIL'),
    'admin_email' => env('PORTFOLIO_ADMIN_EMAIL'),
    'social' => [
        'github' => env('PORTFOLIO_GITHUB') ?: 'https://github.com/brt9',
        'linkedin' => env('PORTFOLIO_LINKEDIN') ?: 'https://www.linkedin.com/in/pedrofelipebrt9',
    ],
    'headline' => 'Transformo processos operacionais em sistemas, integrações e automações que as equipes realmente conseguem usar.',
    'about' => 'Sou desenvolvedor Full Stack e Analista de Implantação, com experiência em Laravel, PHP, JavaScript, PostgreSQL e MySQL. Atuo da análise de regras de negócio à implantação, homologação e suporte, criando aplicações web, APIs, painéis e automações com foco em confiabilidade, rastreabilidade e decisões orientadas por dados.',
    'profile_source' => 'linkedin_pdf',
    'profile_updated_at' => '2026-06-21',
    'stats' => [
        ['value' => '10+ anos', 'label' => 'Experiência operacional'],
        ['value' => 'Laravel', 'label' => 'Stack principal'],
        ['value' => '3', 'label' => 'Experiências em destaque'],
        ['value' => 'Natal/RN', 'label' => 'Brasil'],
    ],
    'competencies' => [
        [
            'title' => 'Backend',
            'description' => 'APIs, regras de negócio, persistência e integrações resilientes para sistemas que precisam continuar operando.',
            'items' => ['Laravel', 'PHP 8', 'APIs REST', 'PostgreSQL', 'MySQL', 'Pest', 'Docker'],
        ],
        [
            'title' => 'Frontend',
            'description' => 'Interfaces responsivas que organizam fluxos complexos e mantêm as ações importantes fáceis de encontrar.',
            'items' => ['JavaScript', 'Blade', 'Vue.js', 'Alpine.js', 'Tailwind CSS', 'Bootstrap', 'Vite'],
        ],
        [
            'title' => 'Dados e BI',
            'description' => 'Consultas, indicadores e painéis que transformam registros operacionais em decisões rastreáveis.',
            'items' => ['PostgreSQL', 'MySQL', 'SQL', 'Power BI', 'Dashboards'],
        ],
        [
            'title' => 'Implantação',
            'description' => 'Configuração, homologação, treinamento e suporte para levar o produto do ambiente técnico ao uso real.',
            'items' => ['Homologação', 'Suporte', 'Documentação', 'Treinamento', 'Nginx'],
        ],
        [
            'title' => 'Infraestrutura e qualidade',
            'description' => 'Ambientes reproduzíveis, testes automatizados e pipelines que reduzem falhas durante a entrega.',
            'items' => ['Docker', 'Git', 'GitHub Actions', 'Pest', 'CI/CD'],
        ],
        [
            'title' => 'Geo e automação',
            'description' => 'Mapas, scripts e aplicações instaláveis que simplificam tarefas repetitivas e fluxos de campo.',
            'items' => ['QGIS', 'GeoJSON', 'PowerShell', 'IA', 'PWA'],
        ],
    ],
    'experience' => [
        [
            'period' => '01/2026 — atual',
            'role' => 'Analista de Implantação',
            'company' => 'Vox Tecnologia',
            'location' => 'Natal, RN',
            'description' => 'Implantação, homologação e suporte do SIGFácil, além da criação de ferramentas internas, automações, relatórios, dashboards e indicadores ligados à abertura e ao licenciamento de empresas. Atuação com dados, sistemas web, APIs e PostgreSQL.',
            'stack' => ['Laravel', 'PHP', 'JavaScript', 'Docker', 'PostgreSQL', 'Power BI', 'QGIS'],
        ],
        [
            'period' => '01/2023 — atual',
            'role' => 'Desenvolvedor Full Stack Freelancer',
            'company' => 'Projetos independentes',
            'location' => 'Remoto',
            'description' => 'Desenvolvimento de sistemas de gestão sob medida para controle de ponto, estoque e dashboards, cobrindo levantamento, arquitetura, implementação, publicação, treinamento e evolução.',
            'stack' => ['Laravel', 'PHP 8', 'JavaScript', 'Vue.js', 'Alpine.js', 'APIs', 'Tailwind CSS'],
        ],
        [
            'period' => '10/2015 — 02/2026',
            'role' => 'Operador de Sistema',
            'company' => 'CAERN — Companhia de Águas e Esgotos do RN',
            'location' => 'Natal, RN',
            'description' => 'Gestão operacional de almoxarifado e criação do BardoTI, utilizado desde maio de 2023 para solicitações, rastreamento em tempo real, relatórios, rastreabilidade por QR Code e código de barras e integração com Power BI.',
            'stack' => ['PHP', 'Laravel', 'JavaScript', 'MySQL', 'Power BI', 'PWA', 'QR Code'],
        ],
    ],
    'education' => [
        [
            'course' => 'Bacharelado em Sistemas de Informação',
            'institution' => 'Universidade Potiguar — UnP',
            'period' => '06/2019 — 06/2023',
        ],
    ],
    'languages' => [
        ['name' => 'Português', 'level' => 'Nativo ou bilíngue'],
        ['name' => 'Inglês', 'level' => 'Profissional'],
    ],
    'language_note' => 'Vivência internacional por 1 ano e 11 meses.',
    'projects' => [
        [
            'number' => '01',
            'title' => 'BardoTI',
            'context' => 'Solicitações e movimentações de materiais exigiam rastreabilidade e visibilidade operacional.',
            'action' => 'Criei uma aplicação web com fluxo de solicitações, acompanhamento em tempo real, PWA, QR Code, código de barras e relatórios.',
            'result' => 'Sistema implantado em maio de 2023 e mantido em uso para apoiar a operação e os indicadores no Power BI.',
            'stack' => ['Laravel', 'PHP', 'JavaScript', 'MySQL', 'PWA'],
            'status' => 'Em uso',
            'url' => 'https://www.bardoti.xyz',
        ],
        [
            'number' => '02',
            'title' => 'Portfólio resiliente',
            'context' => 'Uma vitrine profissional não deve desaparecer quando APIs externas ficam indisponíveis.',
            'action' => 'Separei clientes, normalização, banco, cache e estados de falha para agenda, clima, Steam, Duolingo e GitHub.',
            'result' => 'A página preserva os últimos dados válidos e informa com clareza quando cada captura ocorreu.',
            'stack' => ['Laravel', 'Blade', 'PostgreSQL', 'APIs'],
            'status' => 'Ao vivo',
        ],
        [
            'number' => '03',
            'title' => 'Plataforma de RH e ponto',
            'context' => 'A empresa precisava centralizar jornadas, documentos e acessos de colaboradores.',
            'action' => 'Implementei cálculo de ponto, contracheques em PDF, permissões, testes, implantação e documentação.',
            'result' => 'Fluxo administrativo centralizado, com publicação automatizada e equipe treinada.',
            'stack' => ['Laravel', 'MySQL', 'Blade', 'Bootstrap', 'Nginx'],
            'status' => 'Entregue',
        ],
    ],
    'integrations' => [
        'weather' => env('PORTFOLIO_WEATHER_ENABLED', true),
        'calendar' => env('GOOGLE_CALENDAR_ENABLED', false),
        'duolingo' => env('DUOLINGO_ENABLED', false),
        'allow_in_tests' => false,
    ],
];
