version: 2

updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      compatible-composer-updates:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      compatible-frontend-updates:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: nuget
    directory: "/tools/telemetry-agent"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      compatible-agent-updates:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3

  - package-ecosystem: docker
    directory: "/docker/php"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3

  - package-ecosystem: docker
    directory: "/docker/nginx"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      compatible-action-updates:
        patterns: ["*"]
        update-types: ["minor", "patch"]
