<?php

return [
    'name' => env('PORTFOLIO_NAME') ?: 'Pedro Felipe',
    'role' => env('PORTFOLIO_ROLE') ?: 'Desenvolvedor Full Stack',
    'current_role' => 'Analista de Implantação',
    'location' => env('PORTFOLIO_LOCATION') ?: 'Natal, RN · Brasil',
    'company' => env('PORTFOLIO_COMPANY') ?: 'Vox Tecnologia',
    'presentation_timezone' => env('PORTFOLIO_TIMEZONE', 'America/Fortaleza'),
    'photo' => '/images/pedro-felipe.png',
    'email' => env('PORTFOLIO_EMAIL'),
    'admin_email' => env('PORTFOLIO_ADMIN_EMAIL'),
    'social' => [
        'github' => env('PORTFOLIO_GITHUB') ?: 'https://github.com/brt9',
        'linkedin' => env('PORTFOLIO_LINKEDIN') ?: 'https://www.linkedin.com/in/pedrofelipebrt9',
    ],
    'headline' => 'Transformo processos operacionais em sistemas, integrações e automações que as equipes realmente conseguem usar.',
    'about' => 'Sou desenvolvedor Full Stack e Analista de Implantação, com experiência em Laravel, PHP, JavaScript, PostgreSQL e MySQL. Atuo da análise de regras de negócio à implantação, homologação e suporte, criando aplicações web, APIs, painéis e automações com foco em confiabilidade, rastreabilidade e decisões orientadas por dados.',
    'profile_source' => 'linkedin_pdf',
    'profile_updated_at' => '2026-06-21',
    'stats' => [
        ['value' => '10+ anos', 'label' => 'Experiência operacional'],
        ['value' => 'Laravel', 'label' => 'Stack principal'],
        ['value' => '4', 'label' => 'Experiências em destaque'],
        ['value' => 'Natal/RN', 'label' => 'Brasil'],
    ],
    'competencies' => [
        [
            'title' => 'Backend',
            'items' => ['Laravel', 'PHP 8', 'APIs REST', 'Integrações', 'Testes'],
            'evidence' => 'Sistemas de gestão, telemetria e integrações resilientes',
            'href' => '#projetos',
        ],
        [
            'title' => 'Frontend',
            'items' => ['JavaScript', 'Blade', 'Vue.js', 'Alpine.js', 'Bootstrap'],
            'evidence' => 'Interfaces responsivas para operação diária',
            'href' => '#projetos',
        ],
        [
            'title' => 'Dados e BI',
            'items' => ['PostgreSQL', 'MySQL', 'SQL', 'Power BI', 'Dashboards'],
            'evidence' => 'Indicadores, relatórios e rastreabilidade operacional',
            'href' => '#experiencia',
        ],
        [
            'title' => 'Implantação',
            'items' => ['Homologação', 'Suporte', 'Documentação', 'Treinamento', 'Nginx'],
            'evidence' => 'Entrega completa da configuração ao acompanhamento',
            'href' => '#experiencia',
        ],
        [
            'title' => 'Infraestrutura e qualidade',
            'items' => ['Docker', 'Git', 'GitHub Actions', 'Pest', 'CI/CD'],
            'evidence' => 'Ambientes repetíveis, testes e automação de entrega',
            'href' => '#automacoes',
        ],
        [
            'title' => 'Geo e automação',
            'items' => ['QGIS', 'GeoJSON', 'PowerShell', 'IA', 'PWA'],
            'evidence' => 'Ferramentas internas e fluxos operacionais automatizados',
            'href' => '#automacoes',
        ],
    ],
    'experience' => [
        [
            'period' => '01/2026 — atual',
            'role' => 'Analista de Implantação',
            'company' => 'Vox Tecnologia',
            'location' => 'Natal, RN',
            'description' => 'Implantação, homologação e suporte do SIGFácil, além da criação de ferramentas internas, automações, relatórios, dashboards e indicadores ligados à abertura e ao licenciamento de empresas. Atuação com dados, sistemas web, APIs e PostgreSQL.',
            'stack' => ['Laravel', 'PHP', 'JavaScript', 'Docker', 'PostgreSQL', 'Power BI', 'QGIS'],
        ],
        [
            'period' => '01/2023 — atual',
            'role' => 'Desenvolvedor Full Stack Freelancer',
            'company' => 'Projetos independentes',
            'location' => 'Remoto',
            'description' => 'Desenvolvimento de sistemas de gestão sob medida para controle de ponto, estoque e dashboards, cobrindo levantamento, arquitetura, implementação, publicação, treinamento e evolução.',
            'stack' => ['Laravel', 'PHP 8', 'JavaScript', 'Vue.js', 'Alpine.js', 'APIs', 'Tailwind CSS'],
        ],
        [
            'period' => '10/2015 — 02/2026',
            'role' => 'Operador de Sistema',
            'company' => 'CAERN — Companhia de Águas e Esgotos do RN',
            'location' => 'Natal, RN',
            'description' => 'Gestão operacional de almoxarifado e criação do BardoTI, utilizado desde maio de 2023 para solicitações, rastreamento em tempo real, relatórios, rastreabilidade por QR Code e código de barras e integração com Power BI.',
            'stack' => ['PHP', 'Laravel', 'JavaScript', 'MySQL', 'Power BI', 'PWA', 'QR Code'],
        ],
        [
            'period' => '02/2025 — 01/2026',
            'role' => 'Desenvolvedor Full Stack Freelancer',
            'company' => 'Teixeira Construções / ETS',
            'location' => 'Remoto',
            'description' => 'Plataforma de RH e ponto eletrônico com cálculo de jornadas, contracheques em PDF, gestão de colaboradores e permissões, testes, publicação com Nginx, treinamento e documentação.',
            'stack' => ['Laravel', 'MySQL', 'Blade', 'Bootstrap', 'Nginx', 'CI/CD'],
        ],
    ],
    'education' => [
        [
            'course' => 'Bacharelado em Sistemas de Informação',
            'institution' => 'Universidade Potiguar — UnP',
            'period' => '06/2019 — 06/2023',
        ],
    ],
    'languages' => [
        ['name' => 'Português', 'level' => 'Nativo ou bilíngue'],
        ['name' => 'Inglês', 'level' => 'Profissional'],
    ],
    'projects' => [
        [
            'number' => '01',
            'title' => 'BardoTI',
            'context' => 'Solicitações e movimentações de materiais exigiam rastreabilidade e visibilidade operacional.',
            'action' => 'Criei uma aplicação web com fluxo de solicitações, acompanhamento em tempo real, PWA, QR Code, código de barras e relatórios.',
            'result' => 'Sistema implantado em maio de 2023 e mantido em uso para apoiar a operação e os indicadores no Power BI.',
            'stack' => ['Laravel', 'PHP', 'JavaScript', 'MySQL', 'PWA'],
            'status' => 'Em uso',
        ],
        [
            'number' => '02',
            'title' => 'Portfólio resiliente',
            'context' => 'Uma vitrine profissional não deve desaparecer quando APIs externas ficam indisponíveis.',
            'action' => 'Separei clientes, normalização, banco, cache e estados de falha para agenda, clima, Steam, Duolingo e GitHub.',
            'result' => 'A página preserva os últimos dados válidos e informa com clareza quando cada captura ocorreu.',
            'stack' => ['Laravel', 'Blade', 'PostgreSQL', 'APIs'],
            'status' => 'Ao vivo',
        ],
        [
            'number' => '03',
            'title' => 'Plataforma de RH e ponto',
            'context' => 'A empresa precisava centralizar jornadas, documentos e acessos de colaboradores.',
            'action' => 'Implementei cálculo de ponto, contracheques em PDF, permissões, testes, implantação e documentação.',
            'result' => 'Fluxo administrativo centralizado, com publicação automatizada e equipe treinada.',
            'stack' => ['Laravel', 'MySQL', 'Blade', 'Bootstrap', 'Nginx'],
            'status' => 'Entregue',
        ],
    ],
    'automations' => [
        [
            'title' => 'Agente de telemetria para Windows',
            'before' => 'Consultar o estado do computador manualmente em ferramentas locais.',
            'solution' => 'Executável .NET coleta métricas suportadas e envia amostras autenticadas para a API.',
            'result' => 'Leitura centralizada com estados online, defasado e offline calculados pelo servidor.',
            'stack' => ['.NET 8', 'PowerShell', 'Laravel API'],
            'responsibility' => 'Arquitetura, implementação, empacotamento e documentação.',
        ],
        [
            'title' => 'Agenda local com Google opcional',
            'before' => 'A agenda dependia da autorização e da disponibilidade do Google.',
            'solution' => 'CRUD local persistente, sincronização bidirecional controlada e snapshot seguro dos eventos externos.',
            'result' => 'Compromissos continuam disponíveis e editáveis mesmo sem conexão com o provedor.',
            'stack' => ['Laravel', 'Google Calendar API', 'Scheduler'],
            'responsibility' => 'Modelagem, API, sincronização, privacidade e interface.',
        ],
        [
            'title' => 'Clima persistente de Natal',
            'before' => 'Falhas temporárias da API deixavam o card sem informação.',
            'solution' => 'Captura agendada no banco com fallback para o último registro válido e horário visível.',
            'result' => 'O dado mais recente de Natal permanece disponível mesmo durante indisponibilidade externa.',
            'stack' => ['Open-Meteo', 'Laravel Scheduler', 'PostgreSQL'],
            'responsibility' => 'Persistência, expiração, fallback e apresentação.',
        ],
    ],
    'integrations' => [
        'weather' => env('PORTFOLIO_WEATHER_ENABLED', true),
        'calendar' => env('GOOGLE_CALENDAR_ENABLED', false),
        'duolingo' => env('DUOLINGO_ENABLED', false),
        'allow_in_tests' => false,
    ],
];
