<?php

return [
    'name' => env('PORTFOLIO_NAME') ?: 'Pedro Felipe',
    'role' => env('PORTFOLIO_ROLE') ?: 'Desenvolvedor Full Stack',
    'location' => env('PORTFOLIO_LOCATION') ?: 'Natal, RN · Brasil',
    'company' => env('PORTFOLIO_COMPANY') ?: 'CAERN — Companhia de Águas e Esgotos do RN',
    'photo' => '/images/pedro-felipe.png',
    'email' => env('PORTFOLIO_EMAIL'),
    'social' => [
        'github' => env('PORTFOLIO_GITHUB') ?: 'https://github.com/brt9',
        'linkedin' => env('PORTFOLIO_LINKEDIN') ?: 'https://www.linkedin.com/in/pedrofelipebrt9',
    ],
    'headline' => 'Transformo regras de negócio em aplicações, integrações e automações web confiáveis.',
    'about' => 'Sou desenvolvedor Full Stack com foco em Laravel, PHP e JavaScript. Trabalho do backend à interface para criar sistemas fáceis de operar e manter, com validação, testes, tratamento de falhas e atenção à experiência de quem usa.',
    'stats' => [
        ['value' => 'Laravel 12', 'label' => 'Base do projeto'],
        ['value' => 'PHP 8.3', 'label' => 'Backend moderno'],
        ['value' => '3', 'label' => 'Integrações ao vivo'],
        ['value' => 'Natal/RN', 'label' => 'Brasil'],
    ],
    'competencies' => [
        [
            'title' => 'Backend',
            'items' => ['Laravel', 'PHP', 'APIs REST', 'Validação', 'Cache'],
            'evidence' => 'API de telemetria e integrações resilientes',
            'href' => '#projetos',
        ],
        [
            'title' => 'Frontend',
            'items' => ['JavaScript', 'Blade', 'Alpine.js', 'Tailwind CSS', 'Chart.js'],
            'evidence' => 'Interface responsiva e histórico acessível',
            'href' => '#lab',
        ],
        [
            'title' => 'Dados',
            'items' => ['PostgreSQL', 'MySQL', 'SQL', 'Retenção', 'Agregações'],
            'evidence' => 'Histórico temporal sem interpolar lacunas',
            'href' => '#lab',
        ],
        [
            'title' => 'Infraestrutura e qualidade',
            'items' => ['Docker', 'Git', 'GitHub Actions', 'Pest', 'Vite'],
            'evidence' => 'Pipeline, testes e verificações de segurança',
            'href' => '#automacoes',
        ],
        [
            'title' => 'Integrações',
            'items' => ['Steam Web API', 'Open-Meteo', 'GitHub API', 'HTTP Client'],
            'evidence' => 'Dados externos com cache e estados de falha',
            'href' => '#integracoes',
        ],
        [
            'title' => 'Automação',
            'items' => ['.NET', 'PowerShell', 'Scheduler', 'Scripts operacionais'],
            'evidence' => 'Agente Windows e manutenção programada',
            'href' => '#automacoes',
        ],
    ],
    'experience' => [
        [
            'period' => '2022 — atual',
            'role' => 'Desenvolvedor Full Stack',
            'company' => 'CAERN — Companhia de Águas e Esgotos do RN',
            'description' => 'Desenvolvimento e evolução de aplicações web, APIs REST e integrações com foco em confiabilidade, automação e manutenção sustentável.',
            'stack' => ['Laravel', 'PHP', 'MySQL', 'Redis'],
        ],
        [
            'period' => '2020 — 2022',
            'role' => 'Desenvolvedor PHP / JavaScript',
            'company' => 'Projetos independentes',
            'description' => 'Modernização de projetos PHP, construção de interfaces responsivas e otimização de consultas e fluxos de desenvolvimento.',
            'stack' => ['PHP', 'JavaScript', 'SQL', 'Git'],
        ],
    ],
    'projects' => [
        [
            'number' => '01',
            'title' => 'Portfólio resiliente',
            'context' => 'Uma vitrine profissional não pode depender da disponibilidade de serviços externos.',
            'action' => 'Separei clientes, normalização, cache e estados de erro para Steam, clima e GitHub.',
            'result' => 'A página principal continua útil mesmo quando todas as integrações falham.',
            'stack' => ['Laravel', 'Blade', 'HTTP Client', 'Cache'],
            'status' => 'Testado',
        ],
        [
            'number' => '02',
            'title' => 'Telemetria Windows',
            'context' => 'Sensores diferentes podem não existir, retornar zero ou ficar temporariamente sem leitura.',
            'action' => 'Criei um agente .NET autenticado, ingestão idempotente, persistência temporal e gráficos com lacunas explícitas.',
            'result' => 'CPU, GPU, memória, disco e uptime aparecem ao vivo sem transformar ausência de dado em valor falso.',
            'stack' => ['.NET', 'Laravel API', 'PostgreSQL', 'Chart.js'],
            'status' => 'Ao vivo',
        ],
        [
            'number' => '03',
            'title' => 'Qualidade automatizada',
            'context' => 'Mudanças visuais e integrações aumentam o risco de regressão, vazamento de segredo e layout quebrado.',
            'action' => 'Automatizei testes, auditorias, varredura de segredos, build e uma matriz de seis larguras de tela.',
            'result' => 'Cada alteração pode ser validada de forma repetível antes da publicação.',
            'stack' => ['Pest', 'GitHub Actions', 'Vite', 'Playwright'],
            'status' => 'CI pronta',
        ],
    ],
    'automations' => [
        [
            'title' => 'Agente de telemetria para Windows',
            'before' => 'Consultar o estado do computador manualmente em ferramentas locais.',
            'solution' => 'Executável single-file que coleta métricas suportadas e envia amostras autenticadas para a API.',
            'result' => 'Leitura centralizada no portfólio, com estado online, defasado ou offline calculado pelo servidor.',
            'stack' => ['.NET 8', 'PowerShell', 'Bearer token'],
            'responsibility' => 'Arquitetura, implementação, empacotamento e documentação.',
        ],
        [
            'title' => 'Histórico e retenção programados',
            'before' => 'Amostras brutas crescem continuamente e são caras para consultar no longo prazo.',
            'solution' => 'Rotina horária agrega períodos concluídos e aplica retenção separada para dados brutos e agregados.',
            'result' => 'Consultas permanecem limitadas e períodos sem leitura continuam visíveis como lacunas.',
            'stack' => ['Laravel Scheduler', 'PostgreSQL', 'SQL'],
            'responsibility' => 'Modelagem, idempotência, consultas e testes de retenção.',
        ],
        [
            'title' => 'Gate local de qualidade',
            'before' => 'Build, responsividade, dependências e segredos eram verificações independentes e manuais.',
            'solution' => 'Scripts executam testes, auditorias, build, secret scan e validação responsiva antes da entrega.',
            'result' => 'O mesmo conjunto de controles pode ser repetido localmente e na integração contínua.',
            'stack' => ['Pest', 'npm audit', 'Composer audit', 'Playwright'],
            'responsibility' => 'Definição dos gates, scripts e cenários de falha.',
        ],
    ],
    'integrations' => [
        'weather' => env('PORTFOLIO_WEATHER_ENABLED', true),
        'allow_in_tests' => false,
    ],
];
